# Generated by Django 5.0.6 on 2026-07-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duts', '0009_dut_inventory_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dut',
            name='a1_address',
            field=models.CharField(blank=True, help_text='A1-P URL（ex: http://10.3.0.71:30183）', max_length=255),
        ),
        migrations.AddField(
            model_name='dut',
            name='description',
            field=models.TextField(blank=True, help_text='受測設備描述'),
        ),
        migrations.AddField(
            model_name='dut',
            name='e2_address',
            field=models.CharField(blank=True, help_text='E2 SCTP 位址:埠（ex: 10.3.0.71:32222）', max_length=255),
        ),
        migrations.AddField(
            model_name='dut',
            name='e2_cell_id',
            field=models.CharField(blank=True, help_text='E2 身分 — Cell ID（ex: 0）', max_length=32),
        ),
        migrations.AddField(
            model_name='dut',
            name='e2_gnb_id',
            field=models.CharField(blank=True, help_text='E2 身分 — gNB ID（ex: 201507）', max_length=32),
        ),
        migrations.AddField(
            model_name='dut',
            name='e2_mcc',
            field=models.CharField(blank=True, help_text='E2 身分 — MCC 行動國碼（ex: 455）', max_length=8),
        ),
        migrations.AddField(
            model_name='dut',
            name='e2_mnc',
            field=models.CharField(blank=True, help_text='E2 身分 — MNC 行動網路碼（ex: 637）', max_length=8),
        ),
        migrations.AddField(
            model_name='dut',
            name='o1_address',
            field=models.CharField(blank=True, help_text='O1 NETCONF 位址:埠（ex: 10.3.0.71:30830）', max_length=255),
        ),
        migrations.AddField(
            model_name='dut',
            name='o1_password',
            field=models.CharField(blank=True, help_text='O1 NETCONF 密碼', max_length=255),
        ),
        migrations.AddField(
            model_name='dut',
            name='o1_username',
            field=models.CharField(blank=True, help_text='O1 NETCONF 帳號', max_length=120),
        ),
        migrations.AddField(
            model_name='dut',
            name='product',
            field=models.CharField(blank=True, help_text='產品名稱（ex: Acme Near-RT RIC）', max_length=200),
        ),
        migrations.AddField(
            model_name='dut',
            name='version',
            field=models.CharField(blank=True, help_text='產品版本（ex: v2.1.0）', max_length=64),
        ),
    ]
