# Generated by Django 5.0.6 on 2026-05-13 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('persona', models.CharField(blank=True, default='', max_length=64)),
                ('controls', models.JSONField(default=dict)),
                ('output_path', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('generated', 'generated'), ('error', 'error')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('controls_overlay', models.JSONField(default=dict)),
                ('source_file', models.CharField(blank=True, default='', max_length=512)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('claude_session_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('tool', 'tool'), ('system', 'system')], max_length=16)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('chat', 'chat'), ('wizard', 'wizard'), ('subagent', 'subagent'), ('tarball', 'tarball')], max_length=16)),
                ('status', models.CharField(choices=[('running', 'running'), ('ok', 'ok'), ('error', 'error')], default='running', max_length=16)),
                ('log', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.instance')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='api.session')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='api.session'),
        ),
    ]
