# Generated by Django 5.0.6 on 2026-05-14 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'running'), ('done', 'done'), ('error', 'error'), ('interrupted', 'interrupted')], default='running', max_length=16)),
                ('user_message_text', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('claude_session_id_in', models.CharField(blank=True, default='', max_length=128)),
                ('claude_session_id_out', models.CharField(blank=True, default='', max_length=128)),
                ('error_text', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='api.session')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TurnEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('system', 'system'), ('text', 'text'), ('text_delta', 'text_delta'), ('thinking_delta', 'thinking_delta'), ('tool_use', 'tool_use'), ('tool_result', 'tool_result'), ('result', 'result'), ('error', 'error'), ('done', 'done')], max_length=24)),
                ('data', models.JSONField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.turn')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddConstraint(
            model_name='turnevent',
            constraint=models.UniqueConstraint(fields=('turn', 'seq'), name='turnevent_seq_uniq'),
        ),
    ]
